/**
 * Document Service — generates Markdown (.md) documents for warehouse and
 * business operations, always including a QR code and a barcode.
 *
 * Every operation (supply order, issue order, invoice, movement) gets a
 * printable .md document saved under server/data/documents/<type>/<number>.md
 */

const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');
const settingsService = require('./settingsService');
const { barcodeDataUri } = require('./code39Service');

const DOCS_DIR = path.join(__dirname, '..', 'data', 'documents');

function ensureDir(sub) {
  const dir = path.join(DOCS_DIR, sub || '');
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function companyName() {
  const identity = settingsService.siteIdentity();
  return String(settingsService.get('doc_company_name', '') || identity.name);
}

function money(cents, sym) {
  const symbol = sym || 'ج.م';
  return `${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${symbol}`;
}

function esc(text) {
  return String(text || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Generate a QR data URI for arbitrary data */
async function qrDataUri(data) {
  try {
    return await QRCode.toDataURL(String(data), { errorCorrectionLevel: 'M', margin: 2, width: 220 });
  } catch {
    return null;
  }
}

/**
 * Build a Markdown document.
 *
 * @param {object} opts
 * @param {string} opts.type      - Document type key (e.g. 'SUP', 'ISS', 'INV', 'MOV')
 * @param {string} opts.title     - Document title (e.g. 'Supply Order')
 * @param {string} opts.number    - Document number (e.g. 'SUP-2026-0001')
 * @param {string} [opts.subtitle] - Second header line
 * @param {Array<[string,string]>} opts.meta - Key/value metadata rows
 * @param {Array<{name:string, qty:number|string, price?:number, amount?:number, extra?:string}>} opts.items
 * @param {Array<[string,string]>} [opts.totals] - Total rows (label, value)
 * @param {string} [opts.footer]   - Footer text
 * @param {string} [opts.qrData]   - Raw data encoded in the QR code (defaults to number)
 * @param {string} [opts.barcode]  - Barcode text (defaults to number)
 * @param {boolean} [opts.currency] - Currency symbol for money columns
 * @returns {Promise<{content: string, filename: string, path: string}>}
 */
async function buildMarkdownDocument(opts) {
  const {
    type, title, number, subtitle = '', meta = [], items = [], totals = [],
    footer = '', qrData, barcode, currency,
  } = opts;

  const company = companyName();
  const qrUri = await qrDataUri(qrData !== undefined ? qrData : number);
  const barUri = barcodeDataUri(barcode !== undefined ? barcode : number);

  const lines = [];
  lines.push(`# ${company}`);
  lines.push('');
  lines.push(`## ${esc(title)}`);
  if (subtitle) lines.push(`### ${esc(subtitle)}`);
  lines.push('');
  lines.push(`**Document No:** ${esc(number)}`);
  lines.push(`**Generated:** ${new Date().toLocaleString('en-GB')}`);
  lines.push('');

  if (meta.length > 0) {
    lines.push('| Field | Value |');
    lines.push('|-------|-------|');
    meta.forEach(([k, v]) => lines.push(`| ${esc(k)} | ${esc(v)} |`));
    lines.push('');
  }

  if (items.length > 0) {
    lines.push('| # | Item | Qty | Unit Price | Amount |');
    lines.push('|---|------|-----|-----------|--------|');
    items.forEach((item, i) => {
      const unit = item.price !== undefined ? money(item.price, currency) : '—';
      const amount = item.amount !== undefined
        ? money(item.amount, currency)
        : (item.price !== undefined ? money(item.price * (item.qty || 1), currency) : '—');
      lines.push(`| ${i + 1} | ${esc(item.name)} | ${item.qty} | ${unit} | ${amount} |`);
    });
    lines.push('');
  }

  if (totals.length > 0) {
    lines.push('| | |');
    lines.push('|---|---|');
    totals.forEach(([label, value]) => lines.push(`| **${esc(label)}** | **${esc(value)}** |`));
    lines.push('');
  }

  // QR + barcode side by side
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| ![QR](${qrUri}) | ![Barcode](${barUri}) |`);
  lines.push('');
  if (footer) {
    lines.push(`---`);
    lines.push(`${esc(footer)}`);
    lines.push('');
  }
  lines.push(`_Generated by ${company} — ${title} ${esc(number)}_`);
  lines.push('');

  const content = lines.join('\n');
  const safeNumber = String(number).replace(/[^A-Za-z0-9._-]/g, '_');
  const dir = ensureDir(type);
  const filename = `${safeNumber}.md`;
  const filePath = path.join(dir, filename);
  fs.writeFileSync(filePath, content, 'utf8');

  return { content, filename, path: filePath };
}

function listDocuments(type) {
  const dir = path.join(DOCS_DIR, type || '');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => {
      const st = fs.statSync(path.join(dir, f));
      return { filename: f, size: st.size, created: st.mtime.toISOString() };
    })
    .sort((a, b) => b.created.localeCompare(a.created));
}

function documentPath(type, filename) {
  return path.join(DOCS_DIR, type, path.basename(filename));
}

module.exports = {
  buildMarkdownDocument,
  listDocuments,
  documentPath,
  DOCS_DIR,
};
